<?php
# This file was automatically generated by the MediaWiki 1.41.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgArticlePath = "/w/$1";

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "UniWiki";

$wgSMTP  =  [ 
    'host'       =>  'ssl://unipro.sakura.ne.jp' ,  // IP アドレスも指定できます。SMTP サーバーのアドレスを指定します。 SSL または TLS を使用する場合は、プレフィックス「ssl://」を追加しますまたは「tls://」。
    'IDHost'     =>  'wiki.uniproject-tech.net' ,       // 通常、これは Web サイト (別名 mywiki.org) のドメイン名になります
    'localhost'  =>  'wiki.uniproject-tech.net' ,       // 上記の IDHost と同じ。一部のメール サーバーで必要です
    'port'       =>  465 ,                 // SMTP サーバーに接続する際にポートを使用する
    'auth'       =>  true ,                // SMTP 認証を使用するかどうか (true または false) 
    'username'   =>  'webmaster@mail.uniproject-tech.net' ,      // SMTP認証に使用するユーザー名 (使用する場合) 
    'password'   =>  'webM@sTer20945'        // SMTP認証に使用するパスワード (使用する場合) 
];
$wgAllowHTMLEmail = true;
$wgDebugLogGroups['mail'] = '/var/www/html/mail.log';

$wgCookieDomain = ".uniproject-tech.net";

define("NS_UNIPRO", 3000);
define("NS_UNIPRO_TALK", 3001);
$wgExtraNamespaces[NS_UNIPRO] = "UniPro";
$wgExtraNamespaces[NS_UNIPRO_TALK] = "UniPro_talk"; 

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://wiki.uniproject-tech.net";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/images/a/ae/UniProLogo.png",
	'icon' => "$wgResourceBasePath/images/a/ae/UniProLogo.png",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "webmaster@mail.uniproject-tech.net";
$wgPasswordSender = "webmaster@mail.uniproject-tech.net";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "172.16.150.100";
$wgDBname = "main_wiki";
$wgDBuser = "root";
$wgDBpassword = "rooterUnipro0001";

# MySQL specific settings
$wgDBprefix = "main_";
$wgDBssl = true;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";
$wgSharedTables[] = 'filearchive';
$wgUploadPath = '/images';
$wgUploadDirectory = '/var/www/html/images';
$wgSharedDB = 'main_wiki';
$wgSharedDBprefix = 'main_';

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "ja";

# Time zone
$wgLocaltimezone = "Asia/Tokyo";
$oldtz = getenv("TZ");
putenv("TZ=$wgLocaltimezone");
# Versions before 1.7.0 used $wgLocalTZoffset as hours.
# After 1.7.0 offset as minutes
$wgLocalTZoffset = date("Z") / 60;
putenv("TZ=$oldtz");

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "1f48db1e8628dd8ab41297cbb45005c5174452b0e5fb3f9d85df37e5ea9b0e3d";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "5742c77f8c97035a";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = "(c)UniProject 2024"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-nc-sa/4.0/";
$wgRightsText = "クリエイティブ・コモンズ 表示-非営利-継承";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-nc-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "minerva";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'AbuseFilter' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'DiscussionTools' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Linter' );
wfLoadExtension( 'LoginNotify' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );

wfLoadExtension( 'Babel' );
$wgBabelCategoryNames = [
	'0' => 'User %code%-0',
	'1' => 'User %code%-1',
	'2' => 'User %code%-2',
	'3' => 'User %code%-3',
	'4' => 'User %code%-4',
	'5' => 'User %code%-5',
	'N' => 'User %code%-N',
];
$wgBabelMainCategory = 'User %code%';
$wgBabelCategorizeNamespaces = [ NS_USER ];
$wgBabelCategoryOverride = true;
$wgBabelAutoCreate = true;

wfLoadExtension( 'Disambiguator' );
wfLoadExtension( 'NewUserMessage' );
wfLoadExtension( 'CheckUser' );

# End of automatically generated settings.
# Add more configuration options below.