apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o ./
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mediawiki
  name: mediawiki
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: mediawiki
  type: LoadBalancer
