apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath -o ./
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath -o ./
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/downloads-default: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: main_wiki
            - name: MYSQL_PASSWORD
              value: wikiSys001
            - name: MYSQL_ROOT_PASSWORD
              value: rooterUnipro0001
            - name: MYSQL_USER
              value: wikiSys
          image: mysql:5.7.28
          name: db
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dbvol
      restartPolicy: Always
      volumes:
        - name: dbvol
          persistentVolumeClaim:
            claimName: db-pvc