apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediawiki
  name: mediawiki
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: mediawiki
  type: ClusterIP
