---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wiki-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: db
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/wiki/db