---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wiki-db-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-db-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: db-data
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/wiki/db