---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-sql
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: db-pvc
  nfs:
    server: 172.16.110.199
    path: /nfs/wiki/db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-img
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: img-pvc
  nfs:
    server: 172.16.110.199
    path: /nfs/wiki/image
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-delimg
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: delimg-pvc
  nfs:
    server: 172.16.110.199
    path: /nfs/wiki/del-image
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    app: mysql
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: img-pvc
  labels:
    app: mediawiki
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delimg-pvc
  labels:
    app: mediawiki
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi