---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-images
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: image
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/wiki/image
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-delimages
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: delimage
  nfs:
    server: nfs.unipro.infra
    path: /nfs/infra/wiki/del-image
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image
  labels:
    app: mediawiki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wiki-images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delimages
  labels:
    app: mediawiki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wiki-delimages