apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediawiki
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - image: localhost:32000/mediawiki:1.1.1
          name: wiki
          envFrom:
          - secretRef:
              name: mediawiki-env
              optional: true
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html/images
              name: imgvol
            - mountPath: /var/www/html/del-images
              name: delimgvol
            - name: mediawiki-config
              mountPath: /var/www/html/LocalSettings.php
              subPath: LocalSettings.php
      restartPolicy: Always
      volumes:
        - name: imgvol
          persistentVolumeClaim:
            claimName: img-pvc
        - name: delimgvol
          persistentVolumeClaim:
            claimName: delimg-pvc
        - name: mediawiki-config
          configMap:
            name: mediawiki-config
