---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-image
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: imgage
  nfs:
    server: 172.16.110.199
    path: /nfs/infra/wiki/image
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-delimage
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: mediawiki
    name: delimage
  nfs:
    server: 172.16.110.199
    path: /nfs/infra/wiki/del-image
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image
  labels:
    app: mediawiki
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wiki-image
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delimage
  labels:
    app: mediawiki
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wiki-delimage